export const WHATSAPP_CLICK_SOURCE_LABELS_AR: Record<string, string> = {
  product_inquiry: 'استفسار من صفحة المنتج',
  product_direct_order: 'طلب مباشر من صفحة المنتج',
  product_sticky_cta: 'زر الشراء الثابت في المنتج',
  quick_order: 'صفحة جهّز طلبك خلال دقيقة',
  homepage_shop_cta: 'زر واتساب في الرئيسية',
  homepage_bundle: 'باقات الصفحة الرئيسية',
  offers_hero_whatsapp: 'واتساب صفحة العروض',
  offers_bundle: 'باقات صفحة العروض',
  restaurants_hero_whatsapp: 'واتساب صفحة المطاعم والكافيهات',
  restaurants_bundle: 'باقات صفحة المطاعم والكافيهات',
  restaurants_empty_whatsapp: 'واتساب صفحة المطاعم (الحالة الفارغة)',
  packaging_hero_whatsapp: 'واتساب صفحة التغليف',
  packaging_bundle: 'باقات التغليف',
  packaging_empty_whatsapp: 'واتساب عدم توفر منتجات التغليف',
  plastics_hero_whatsapp: 'واتساب صفحة البلاستيكيات',
  plastics_bundle: 'باقات البلاستيكيات',
  plastics_empty_whatsapp: 'واتساب عدم توفر منتجات البلاستيكيات',
  mobile_menu_whatsapp: 'واتساب القائمة الجانبية',
  footer_whatsapp: 'واتساب الفوتر',
};
